mysite/urls.py
from django.contrib import admin
from django.urls import path
from p_library import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.books_list),
    path('index/', views.index),
    path("index/book_increment/", views.book_increment),
    path("index/book_decrement/", views.book_decrement),
    path("index/redactions/", views.redaction),
]

p_library/models.py
from django.db import models

class Author(models.Model):
    full_name = models.TextField()  
    birth_year = models.SmallIntegerField()  
    country = models.CharField(max_length=2)

    class Meta:
        verbose_name = "Authors of book"

    def __str__(self):
        return self.full_name

class Redaction(models.Model):
    name=models.TextField()

    def __str__(self):
        return self.name

class Book(models.Model):
    ISBN = models.CharField(max_length=13)
    title = models.TextField()
    description = models.TextField()
    year_release = models.SmallIntegerField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    copy_count = models.SmallIntegerField(default=1)
    price=models.DecimalField(max_digits=10, decimal_places=2)
    redaction = models.ForeignKey(Redaction, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

p_library/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.views.decorators.csrf import csrf_exempt
from p_library.models import Book, Redaction
from django.template import loader



def books_list(request):
    books = Book.objects.all()
    return HttpResponse(books)

def index(request):
    template = loader.get_template("index.html")
    books = Book.objects.all()
    biblio_data = {"title": "мою библиотеку", 'books': books}
    return HttpResponse(template.render(biblio_data, request))

@csrf_exempt
def book_increment(request):
    if request.method == "POST":
        book_id = request.POST["id"]
        if not book_id:
            return redirect("/index/")
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect("/index/")
            book.copy_count += 1
            book.save()
        return redirect("/index/")
    else:
        return redirect("index/")

@csrf_exempt
def book_decrement(request):
    if request.method == "POST":
        book_id = request.POST["id"]
        if not book_id:
            return redirect("/index/")
        else:
            book = Book.objects.filter(id = book_id).first()
            if not book:
                return redirect("/index/")
            if book.copy_count < 0:
                book.copy_count = 0
            else:
                book.copy_count -= 1
            book.save()
        return redirect("/index/")
    else:
        return redirect("/index/")

def redaction(request):
    template = loader.get_template("redactions.html")
    books = Book.objects.all()
    redactions = Redaction.objects.all()
    books_data = {"books": books, "redactions": redactions}
    return HttpResponse(template.render(books_data))

p_library/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
    <title>{%block title%}{% endblock %}</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <script src="{% static 'js/bootstrap.min.js' %} "></script>
  {% block extra_head %}{% endblock %}
</head>

<body>
    <div class="container mt-5">
        {% block main_content %}
        {% endblock %}
    </div>
    

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="{% static 'js/script.js' %} "></script>
</body>

</html>

p_library/templates/index.html
Добро пожаловать в {{ title }}.  <br>
Тут собрано {{ books|length }} книг из моей личной коллекции. <br>

<table border="1">
        <thead>
            <tr>
                <th>"Индекс"</th>
                <th>"ISBN"</th>
                <th>"Количество"</th>
                <th>"Название"</th>
                <th>"Дата публикации"</th>
                <th>"Автор"</th>
                <th>"Страна"</th>
                <th>"Краткое описаниеЭ</th>
                <th>"Цена"</th>
            </tr>
        </thead>
    {% for book in books %}
        
        <tbody>
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{book.ISBN}}</td>
                <td>{{book.copy_count}}</td>
                <td>{{book.title}}</td>
                <td>{{ book.year_release }}</td>
                <td>{{ book.author.full_name }}</td>
                <td>{{ book.author.country }}</td>
                <td>{{book.description}}</td>
                <td>{{book.price}} руб.</td>
                <td>
                    <form action="/index/book_increment/" method="post" enctype="multipart/form-data">
                        <input type="hidden" name="id" value="{{book.id}}">
                        <input type="submit" value="Увеличить количество">
                    </form>
                    <form action="/index/book_decrement/" method="post" enctype="multipart/form-data">
                        <input type="hidden" name="id" value="{{book.id}}">
                        <input type="submit" value="Уменьшить количество">
                    </form>
                </td>
            </tr>
        </tbody>
    {% endfor %}
</table>

p_library/templates/redactions.html
{% extends 'base.html' %}

{% block main_content %}

        <h1 class="display-4">Список литературы</h1>
        <ul class="list-group  list-group-flush">
            {% for redaction in redactions %}
                <ul class="list-group"><h1 class="h4 text-left font-weight-bold mt-5">{{redaction}}</h1></ul>
                {% for book in redaction.book_set.all %}
                    <li class="list-group-item list-group-item-action ml-3" >
                        <p class="font-weight-bold">{{book}}</p> <p class="font-italic">{{book.author}}</p> <p class="font-weight-light">{{book.description}}</p>
                        <span {% if book.price <= 500.0 %}class="badge badge-secondary badge-danger"{% else %}class="badge badge-secondary"{% endif %}>
                                {{book.price}} руб. {% if book.price <= 200.0 %}СКИДКА!!!!{% endif %}
                        </span> <span class="badge badge-pill badge-warning">{% if book.copy_count == 2 %}Осталось всего {{book.copy_count}} книги {% elif book.copy_count == 1 %}Осталась всего {{book.copy_count}} книга!!! {% endif %}</span></li>
                {% endfor %}
            {% endfor %}
        </ul>
   


{% endblock %}